### ISSUE TITLE
Artisan always prints using the left extruder

### ISSUE THREAD

**Issue by raleksandar** [Snapmaker/SnapmakerCuraPlugin#50]
I've just tested the v0.6.0 pre-release version with Artisan. I want to print a model using the right extruder, and even though I've configured that in Cura (it painted the model with the correct color in the preview), once the gcode is exported and loaded on Artisan, the model was printed using the left extruder.

I have tried disabling the left extruder in Cura, but that made no difference. What else can I try?

**Comment by sumibin** [comment]
Make sure you are not using a left extruder in your extruder setup. Otherwise, this is what happens in the picture above.

![image](https://user-images.githubusercontent.com/34013829/225853677-c474b0e6-eb86-42a4-bcf8-4a8b3752ff4f.png)

**Comment by raleksandar** [comment]
Checked that before posting.
Also, when I disable the left extruder Cura hides all options where you can configure the extruder to use (the pictured option is not available when only one extruder is enabled in `Settings > Left/Right Extruder > Disable Extruder`)

**Comment by tensile23** [comment]
I think it's a cura usage issue. When you disable an extruder, the resulting Gcode will have only one T1 instruction.
In addition, you are required to upgrade the firmware of Artsian to the latest. （(In older firmware, G28 causes the activation nozzle to switch to T0)
![image](https://user-images.githubusercontent.com/34013829/228714627-7f07f0d4-ec45-4829-8375-563b658cf052.png)

![image](https://user-images.githubusercontent.com/34013829/228714486-e7af8842-304e-4cd5-829b-45c58458534b.png)
