### ISSUE TITLE
unable to change extruder speed printing

### ISSUE THREAD

**Issue by Pitive** [Snapmaker/SnapmakerCuraPlugin#63]
in the print profile settings for Snapmaker Artisan , the print speed fields are disabled and set with 100 mm/s.
Which is too fast for several materials.

**Comment by parachvte** [comment]
Please checkout [Release 0.8.0](https://github.com/Snapmaker/SnapmakerCuraPlugin/releases/tag/0.8.0)

parameter relations should be fixed by now.
