### ISSUE TITLE
[FR] Use ufp files instead of gcode

### ISSUE THREAD

**Issue by jellespijker** [Snapmaker/SnapmakerCuraPlugin#71]
During review of the plugin (v0.9.0) in noticed that the binary of a thumbnail was added to the gcode text file.

You might want to take a look at the `ufp` fileformat that we (UltiMaker) use to add such extra information.

It is basically zipped gcode with additional information. We use libCharon (Python module on our printers and in Cura) https://github.com/Ultimaker/libCharon

**Comment by parachvte** [comment]
The G-code text file with thumbnail is an extended version of G-code plaintext. Currently, Firmware of Snapmaker printers uses the information to display thumbnail on the screen.
