### ISSUE TITLE
doesn't send files over wifi and does not generate thumbnail preview

### ISSUE THREAD

**Issue by colombod** [Snapmaker/SnapmakerCuraPlugin#75]
With latest version of cura (5.3.1) the plugin is not giving me the option to send file via network and there is no thumbnail preview.

**Comment by parachvte** [comment]
- Which printer are you using?
   - You need to add a non-networked printer that pre-defined after installing the plugin. 
- Select "Snapmaker Flavor G-code File (*.gcode)" when exporting G-code

**Comment by colombod** [comment]
A350 profile installed and slicing. Doesn't show any other option other than saving to disk

**Comment by colombod** [comment]
How do I send this gcode to the machine?

**Comment by parachvte** [comment]
Could you try out [version 0.9.2](https://github.com/Snapmaker/SnapmakerCuraPlugin/releases/tag/0.9.2)?

In previous version (0.9.0), only Snapmaker 2.0 printers with dual extruder can be found via network.

**Comment by colombod** [comment]
how do I install the pre-release package?

**Comment by parachvte** [comment]
![image](https://github.com/Snapmaker/SnapmakerCuraPlugin/assets/3749551/55c1d606-11d1-41ef-be84-c3b4d1f6aeaa)

There is a section in README, drag downloaded [SnapmakerPlugin-0.9.2.curapackage](https://github.com/Snapmaker/SnapmakerCuraPlugin/releases/download/0.9.2/SnapmakerPlugin-0.9.2.curapackage) into Cura Window and restart Cura will work.

**Comment by colombod** [comment]
should have read first , thank you :)
