### ISSUE TITLE
Cant connect to printer through wifi

### ISSUE THREAD

**Issue by pwvandeursen** [Snapmaker/SnapmakerCuraPlugin#77]
I have installed the cura plugin, added the snapmaker 2 printer and then restarted. added a project, sliced, but no option to send to the printer directly.

Do I need to find the printer in my network first somewhere?

**Comment by pahenning** [comment]
Same questions from my side: How does one teach Cura the IP address of the SnapMaker? If I try to find it on the network during printer installation, Cura is unable to connect.

**Comment by NivO5** [comment]
I have it too, tested from 2 different PCs, and checked windows Firewall settings. The 3rd party plugins work like a charm.

**Comment by NivO5** [comment]
Had it too, upgrading the plugin to 0.9.2 solved it for me.

**Comment by chinloon** [comment]
I am unable to connect to my snapmaker 2 A350 over wifi.  DIscovery doe snot work and there is no connections setting to add IP address when printer is added as local.
